<html>
  <head>
    <title>Code Review :: </title>
    <style type="text/css">
    .body{background-color:White;}
    .summary{width:100%;font-weight:bold;background-color:White;border: thin solid #808000;color:#FAFCFE}
    .outer{font-weight:normal;color:#6D5757;background-color:#FFDFBF}
    .inner{font-weight:normal;color:black;}
    .reviewTable{border: thin solid #C0C0C0; width:100%}
    .headerRow{color:white;background-color: #800000;font-weight:bold;text-align: center}
    .reviewRow{background-color:#FFDFBF;color:black;}
    .rAligned{text-align:right;}
    .data{visibility:hidden}
  </style>
  </head>
  <body class="body">
    <div class="summary">
      <table>
        <tr>
          <td colspan="3" class="headerRow">Review Summary</td>
        </tr>
        <tr class="outer">
          <td>Project Name : <label class="inner" /></td>
          <td>Reviewed By : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Project Code : <label class="inner" /></td>
          <td>Reviewed Date : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Name : <label class="inner" /></td>
          <td>Status : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Version : <label class="inner" /></td>
          <td>Review Preparation Effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Size (ekloc) : <label class="inner" /></td>
          <td>Review effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Release Date for Review : <label class="inner" /></td>
          <td>Rework effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken By : <label class="inner" /></td>
          <td>Review Efficiency : <label class="inner">NaN</label></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken Date : <label class="inner" /></td>
          <td />
        </tr>
      </table>
      <table>
        <tr class="headerRow">
          <td colspan="2">Review Details</td>
          <td colspan="2">Defect Status Analysis</td>
          <td colspan="2">Defect Type Analysis</td>
          <td colspan="4">Defect Injected Phase Analysis</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td>Major</td>
          <td>Medium</td>
          <td>Minor</td>
        </tr>
        <tr class="outer">
          <td>Total No of Suggestions</td>
          <td class="inner">163</td>
          <td>Open</td>
          <td class="inner">163</td>
          <td>Logical</td>
          <td class="inner">0</td>
          <td>Initial Project Setup</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total No of Errors</td>
          <td class="inner">0</td>
          <td>On Hold</td>
          <td class="inner">0</td>
          <td>Incomplete</td>
          <td class="inner">0</td>
          <td>Project Initiation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total</td>
          <td class="inner">163</td>
          <td>Closed</td>
          <td class="inner">0</td>
          <td>UI</td>
          <td class="inner">0</td>
          <td>Requirement Analysis</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td>Rejected</td>
          <td class="inner">0</td>
          <td>Exception Handling</td>
          <td class="inner">0</td>
          <td>Architecture and Design</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td>Documentation</td>
          <td class="inner">0</td>
          <td>Implementation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>QA Testing</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>Transition Phase</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="rAligned">Total</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
      </table>
    </div>
    <br />
    <table class="reviewTable">
      <tr class="headerRow">
        <td>#</td>
        <td>Description</td>
        <td>Status</td>
        <td>DefectType</td>
        <td>InjectedPhase</td>
      </tr>
      <tr class="reviewRow">
        <td>1</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>2</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>3</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>4</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>5</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>6</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>7</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>8</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>9</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>10</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>11</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>12</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>13</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>14</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>15</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>16</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>17</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>18</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>19</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>20</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>21</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>22</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>23</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>24</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>25</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>26</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>27</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>28</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>29</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>30</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>31</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>32</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>33</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>34</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>35</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>36</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>37</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>38</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>39</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>40</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>41</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>42</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>43</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>44</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>45</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>46</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>47</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>48</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>49</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>50</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>51</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>52</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>53</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>54</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>55</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>56</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>57</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>58</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>59</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>60</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>61</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>62</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>63</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>64</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>65</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>66</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>67</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>68</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>69</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>70</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>71</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>72</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>73</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>74</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>75</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>76</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>77</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>78</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>79</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>80</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>81</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>82</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>83</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>84</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>85</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>86</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>87</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>88</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>89</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>90</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>91</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>92</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>93</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>94</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>95</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>96</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>97</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>98</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>99</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>100</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>101</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>102</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>103</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>104</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>105</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>106</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>107</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>108</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>109</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>110</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>111</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>112</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>113</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>114</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>115</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>116</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>117</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>118</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>119</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>120</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>121</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>122</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>123</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>124</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>125</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>126</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>127</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>128</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>129</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>130</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>131</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>132</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>133</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>134</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>135</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>136</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>137</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>138</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>139</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>140</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>141</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>142</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>143</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>144</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>145</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>146</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>147</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>148</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>149</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>150</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>151</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>152</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>153</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>154</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>155</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>156</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>157</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>158</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>159</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>160</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>161</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>162</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
      <tr class="reviewRow">
        <td>163</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
    </table>
    <div>
      <br />
    Created with <a href="http://visualstudiogallery.msdn.microsoft.com/d1e40c49-da36-42a5-8d5a-4ebe1feabbc9">ReviewPal</a></div>
    <div class="data">
      <Data id="ReviewPalData">
        <CodeReview xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <Reviews>
            <Review>
              <ReviewId>1</ReviewId>
              <Line>154</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine13</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0013 : KellyPal : SpacingAndNewLine13</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>2</ReviewId>
              <Line>56</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine15</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0015 : KellyPal : SpacingAndNewLine15</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>3</ReviewId>
              <Line>57</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine15</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0015 : KellyPal : SpacingAndNewLine15</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>4</ReviewId>
              <Line>58</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine15</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0015 : KellyPal : SpacingAndNewLine15</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>5</ReviewId>
              <Line>59</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine15</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0015 : KellyPal : SpacingAndNewLine15</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>6</ReviewId>
              <Line>114</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine15</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0015 : KellyPal : SpacingAndNewLine15</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>7</ReviewId>
              <Line>406</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine15</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0015 : KellyPal : SpacingAndNewLine15</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>8</ReviewId>
              <Line>25</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.anyCenter.                                                                         DataGridViewContentAlignment.MiddleCenter |</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>9</ReviewId>
              <Line>26</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.anyCenter.                                                                         DataGridViewContentAlignment.BottomCenter;</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>10</ReviewId>
              <Line>457</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.KeyEntersEditMode.                 (e.KeyCode &gt;= Keys.NumPad0 &amp;&amp; e.KeyCode &lt;= Keys.NumPad9) ||</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>11</ReviewId>
              <Line>458</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.KeyEntersEditMode.                 negativeSignKey == e.KeyCode ||</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>12</ReviewId>
              <Line>459</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.KeyEntersEditMode.                 Keys.Subtract == e.KeyCode) &amp;&amp;</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>13</ReviewId>
              <Line>518</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.Paint.                                      object value, object formattedValue, string errorText, DataGridViewCellStyle cellStyle,</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>14</ReviewId>
              <Line>519</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.Paint.                                      DataGridViewAdvancedBorderStyle advancedBorderStyle, DataGridViewPaintParts paintParts)</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>15</ReviewId>
              <Line>528</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.Paint.                       paintParts &amp; ~(DataGridViewPaintParts.ErrorIcon | DataGridViewPaintParts.ContentForeground));</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>16</ReviewId>
              <Line>612</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.Paint.                                           srcRect, GraphicsUnit.Pixel);</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>17</ReviewId>
              <Line>619</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>IndentAndNewLine4.Paint.                               cellStyle, advancedBorderStyle, DataGridViewPaintParts.ErrorIcon);</HashCode>
              <Severity>Red</Severity>
              <SmellType>IN0004 : KellyPal : IndentAndNewLine4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>18</ReviewId>
              <Line>79</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.DataGridViewNumericUpDownCell.10</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-10</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>19</ReviewId>
              <Line>80</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.DataGridViewNumericUpDownCell.10</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-10</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>20</ReviewId>
              <Line>107</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.set.99</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-99</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>21</ReviewId>
              <Line>667</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.SetDecimalPlaces.99</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-99</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>22</ReviewId>
              <Line>154</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.set.0.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-0.0</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>23</ReviewId>
              <Line>680</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.SetIncrement.0.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-0.0</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>24</ReviewId>
              <Line>318</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.GetAdjustedEditingControlBounds.2</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-2</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>25</ReviewId>
              <Line>329</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.GetAdjustedEditingControlBounds.2</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-2</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>26</ReviewId>
              <Line>599</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.Paint.255</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-255</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>27</ReviewId>
              <Line>602</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.Paint.255</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-255</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>28</ReviewId>
              <Line>21</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>StaticMethodAndFields</HashCode>
              <Severity>Red</Severity>
              <SmellType>SM0001 : KellyPal : StaticMethodAndFields</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>29</ReviewId>
              <Line>24</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>StaticMethodAndFields</HashCode>
              <Severity>Red</Severity>
              <SmellType>SM0001 : KellyPal : StaticMethodAndFields</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>30</ReviewId>
              <Line>44</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>StaticMethodAndFields</HashCode>
              <Severity>Red</Severity>
              <SmellType>SM0001 : KellyPal : StaticMethodAndFields</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>31</ReviewId>
              <Line>46</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>StaticMethodAndFields</HashCode>
              <Severity>Red</Severity>
              <SmellType>SM0001 : KellyPal : StaticMethodAndFields</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>32</ReviewId>
              <Line>50</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>StaticMethodAndFields</HashCode>
              <Severity>Red</Severity>
              <SmellType>SM0001 : KellyPal : StaticMethodAndFields</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>33</ReviewId>
              <Line>54</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>StaticMethodAndFields</HashCode>
              <Severity>Red</Severity>
              <SmellType>SM0001 : KellyPal : StaticMethodAndFields</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>34</ReviewId>
              <Line>772</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>StaticMethodAndFields</HashCode>
              <Severity>Red</Severity>
              <SmellType>SM0001 : KellyPal : StaticMethodAndFields</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>35</ReviewId>
              <Line>248</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.Clone.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>36</ReviewId>
              <Line>265</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.Constrain.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>37</ReviewId>
              <Line>285</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.DetachEditingControl.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>38</ReviewId>
              <Line>314</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.GetAdjustedEditingControlBounds.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>39</ReviewId>
              <Line>346</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.GetErrorIconBounds.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>40</ReviewId>
              <Line>366</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.GetFormattedValue.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>41</ReviewId>
              <Line>395</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.GetPreferredSize.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>42</ReviewId>
              <Line>417</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.InitializeEditingControl.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>43</ReviewId>
              <Line>446</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.KeyEntersEditMode.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>44</ReviewId>
              <Line>472</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.OnCommonChange.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>45</ReviewId>
              <Line>500</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.OwnsEditingNumericUpDown.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>46</ReviewId>
              <Line>517</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.Paint.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>47</ReviewId>
              <Line>627</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.PartPainted.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>48</ReviewId>
              <Line>636</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.PositionEditingControl.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>49</ReviewId>
              <Line>665</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.SetDecimalPlaces.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>50</ReviewId>
              <Line>678</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.SetIncrement.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>51</ReviewId>
              <Line>693</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.SetMaximum.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>52</ReviewId>
              <Line>722</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.SetMinimum.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>53</ReviewId>
              <Line>751</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.SetThousandsSeparator.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>54</ReviewId>
              <Line>763</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.ToString.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>55</ReviewId>
              <Line>772</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownCell.TranslateAlignment.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>56</ReviewId>
              <Line>18</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.VkKeyScan.VkKeyScan</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-VkKeyScan</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>57</ReviewId>
              <Line>18</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Method2</HashCode>
              <Severity>Red</Severity>
              <SmellType>MT0002 : KellyPal : Method2</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>58</ReviewId>
              <Line>21</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>59</ReviewId>
              <Line>24</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>60</ReviewId>
              <Line>29</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultRenderingBitmapWidth.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultRenderingBitmapWidth</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DATAGRIDVIEWNUMERICUPDOWNCELL_defaultRenderingBitmapWidth</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>61</ReviewId>
              <Line>29</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>62</ReviewId>
              <Line>30</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultRenderingBitmapHeight.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultRenderingBitmapHeight</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DATAGRIDVIEWNUMERICUPDOWNCELL_defaultRenderingBitmapHeight</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>63</ReviewId>
              <Line>30</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>64</ReviewId>
              <Line>33</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultDecimalPlaces.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultDecimalPlaces</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DATAGRIDVIEWNUMERICUPDOWNCELL_defaultDecimalPlaces</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>65</ReviewId>
              <Line>33</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>66</ReviewId>
              <Line>35</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultIncrement.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultIncrement</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DATAGRIDVIEWNUMERICUPDOWNCELL_defaultIncrement</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>67</ReviewId>
              <Line>35</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>68</ReviewId>
              <Line>37</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultMaximum.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultMaximum</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DATAGRIDVIEWNUMERICUPDOWNCELL_defaultMaximum</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>69</ReviewId>
              <Line>37</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>70</ReviewId>
              <Line>39</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultMinimum.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultMinimum</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DATAGRIDVIEWNUMERICUPDOWNCELL_defaultMinimum</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>71</ReviewId>
              <Line>39</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>72</ReviewId>
              <Line>41</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultThousandsSeparator.DATAGRIDVIEWNUMERICUPDOWNCELL_defaultThousandsSeparator</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DATAGRIDVIEWNUMERICUPDOWNCELL_defaultThousandsSeparator</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>73</ReviewId>
              <Line>41</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>74</ReviewId>
              <Line>44</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>75</ReviewId>
              <Line>46</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>76</ReviewId>
              <Line>50</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>77</ReviewId>
              <Line>54</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>78</ReviewId>
              <Line>56</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.decimalPlaces.decimalPlaces</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-decimalPlaces</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>79</ReviewId>
              <Line>56</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>80</ReviewId>
              <Line>57</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.increment.increment</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-increment</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>81</ReviewId>
              <Line>57</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>82</ReviewId>
              <Line>58</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>83</ReviewId>
              <Line>59</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>84</ReviewId>
              <Line>60</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable1</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0001 : KellyPal : Variable1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>85</ReviewId>
              <Line>97</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.DecimalPlaces.DecimalPlaces</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-DecimalPlaces</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>86</ReviewId>
              <Line>144</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.Increment.Increment</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-Increment</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>87</ReviewId>
              <Line>248</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>88</ReviewId>
              <Line>265</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.Constrain.Constrain</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-Constrain</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>89</ReviewId>
              <Line>265</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>90</ReviewId>
              <Line>265</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Method2</HashCode>
              <Severity>Red</Severity>
              <SmellType>MT0002 : KellyPal : Method2</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>91</ReviewId>
              <Line>285</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>92</ReviewId>
              <Line>285</Line>
              <Weight>25</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>93</ReviewId>
              <Line>314</Line>
              <Weight>27</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>94</ReviewId>
              <Line>346</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.GetErrorIconBounds.graphics</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-graphics</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>95</ReviewId>
              <Line>348</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Variable4</HashCode>
              <Severity>Red</Severity>
              <SmellType>VR0004 : KellyPal : Variable4</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>96</ReviewId>
              <Line>346</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>97</ReviewId>
              <Line>369</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.GetFormattedValue.valueTypeConverter</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-valueTypeConverter</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>98</ReviewId>
              <Line>370</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.GetFormattedValue.formattedValueTypeConverter</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-formattedValueTypeConverter</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>99</ReviewId>
              <Line>366</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>100</ReviewId>
              <Line>366</Line>
              <Weight>6</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongParameterList.DataGridViewNumericUpDownCell.GetFormattedValue.object value;int rowIndex;DataGridViewCellStyle cellStyle;TypeConverter valueTypeConverter;TypeConverter formattedValueTypeConverter;DataGridViewDataErrorContexts context;</HashCode>
              <Severity>Red</Severity>
              <SmellType>LP0001 : KellyPal : LongParameterList</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>101</ReviewId>
              <Line>366</Line>
              <Weight>24</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>102</ReviewId>
              <Line>366</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>103</ReviewId>
              <Line>367</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>104</ReviewId>
              <Line>368</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>105</ReviewId>
              <Line>369</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>106</ReviewId>
              <Line>370</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>107</ReviewId>
              <Line>395</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.GetPreferredSize.graphics</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-graphics</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>108</ReviewId>
              <Line>395</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.GetPreferredSize.constraintSize</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-constraintSize</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>109</ReviewId>
              <Line>395</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>110</ReviewId>
              <Line>417</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>111</ReviewId>
              <Line>417</Line>
              <Weight>23</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>112</ReviewId>
              <Line>450</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.KeyEntersEditMode.negativeSignStr</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-negativeSignStr</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>113</ReviewId>
              <Line>446</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>114</ReviewId>
              <Line>446</Line>
              <Weight>20</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>115</ReviewId>
              <Line>472</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>116</ReviewId>
              <Line>472</Line>
              <Weight>23</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>117</ReviewId>
              <Line>472</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Method2</HashCode>
              <Severity>Red</Severity>
              <SmellType>MT0002 : KellyPal : Method2</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>118</ReviewId>
              <Line>500</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>119</ReviewId>
              <Line>500</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>Method2</HashCode>
              <Severity>Red</Severity>
              <SmellType>MT0002 : KellyPal : Method2</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>120</ReviewId>
              <Line>517</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.Paint.graphics</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-graphics</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>121</ReviewId>
              <Line>530</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.Paint.ptCurrentCell</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-ptCurrentCell</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>122</ReviewId>
              <Line>517</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>123</ReviewId>
              <Line>517</Line>
              <Weight>11</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongParameterList.DataGridViewNumericUpDownCell.Paint.Graphics graphics;Rectangle clipBounds;Rectangle cellBounds;int rowIndex;DataGridViewElementStates cellState;object value;object formattedValue;string errorText;DataGridViewCellStyle cellStyle;DataGridViewAdvancedBorderStyle advancedBorderStyle;DataGridViewPaintParts paintParts;</HashCode>
              <Severity>Red</Severity>
              <SmellType>LP0001 : KellyPal : LongParameterList</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>124</ReviewId>
              <Line>517</Line>
              <Weight>106</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Red</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>125</ReviewId>
              <Line>517</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>126</ReviewId>
              <Line>518</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>127</ReviewId>
              <Line>627</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>128</ReviewId>
              <Line>636</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>129</ReviewId>
              <Line>636</Line>
              <Weight>9</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongParameterList.DataGridViewNumericUpDownCell.PositionEditingControl.bool setLocation;bool setSize;Rectangle cellBounds;Rectangle cellClip;DataGridViewCellStyle cellStyle;bool singleVerticalBorderAdded;bool singleHorizontalBorderAdded;bool isFirstDisplayedColumn;bool isFirstDisplayedRow;</HashCode>
              <Severity>Red</Severity>
              <SmellType>LP0001 : KellyPal : LongParameterList</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>130</ReviewId>
              <Line>636</Line>
              <Weight>21</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>131</ReviewId>
              <Line>636</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>132</ReviewId>
              <Line>637</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>133</ReviewId>
              <Line>638</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>134</ReviewId>
              <Line>639</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>135</ReviewId>
              <Line>640</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>136</ReviewId>
              <Line>641</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>137</ReviewId>
              <Line>642</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>138</ReviewId>
              <Line>643</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine1</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0001 : KellyPal : SpacingAndNewLine1</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>139</ReviewId>
              <Line>665</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.SetDecimalPlaces.SetDecimalPlaces</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-SetDecimalPlaces</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>140</ReviewId>
              <Line>665</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>141</ReviewId>
              <Line>678</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.SetIncrement.SetIncrement</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-SetIncrement</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>142</ReviewId>
              <Line>678</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>143</ReviewId>
              <Line>693</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>144</ReviewId>
              <Line>693</Line>
              <Weight>23</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>145</ReviewId>
              <Line>722</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>146</ReviewId>
              <Line>722</Line>
              <Weight>23</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>147</ReviewId>
              <Line>751</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>148</ReviewId>
              <Line>763</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>149</ReviewId>
              <Line>772</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.TranslateAlignment.TranslateAlignment</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-TranslateAlignment</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>150</ReviewId>
              <Line>772</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>UnsuitableNaming.DataGridViewNumericUpDownCell.TranslateAlignment.align</HashCode>
              <Severity>Red</Severity>
              <SmellType>UN0001 : KellyPal : UnsuitableNaming-align</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>151</ReviewId>
              <Line>772</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownCell.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LackOfComments</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>152</ReviewId>
              <Line>60</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.get."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>153</ReviewId>
              <Line>68</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.set."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>154</ReviewId>
              <Line>109</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.get."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>155</ReviewId>
              <Line>117</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.set."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>156</ReviewId>
              <Line>157</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.get."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>157</ReviewId>
              <Line>165</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.set."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>158</ReviewId>
              <Line>209</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.get."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>159</ReviewId>
              <Line>217</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.set."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>160</ReviewId>
              <Line>261</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.get."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>161</ReviewId>
              <Line>269</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LiteralConstants.set."Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</HashCode>
              <Severity>Red</Severity>
              <SmellType>LC0001 : KellyPal : LiteralConstants-"Operation cannot be completed because this DataGridViewColumn does not have a CellTemplate."</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>162</ReviewId>
              <Line>242</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>SpacingAndNewLine16.DataGridViewNumericUpDownColumn.ShouldSerializeMinimum.0</HashCode>
              <Severity>Red</Severity>
              <SmellType>SN0016 : KellyPal : SpacingAndNewLine16</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
            <Review>
              <ReviewId>163</ReviewId>
              <Line>1</Line>
              <Weight>1</Weight>
              <File>DataGridViewNumericUpDownColumn.cs</File>
              <Project>DataGridViewNumericUpDownElements</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <Severity>Red</Severity>
              <SmellType>SA0001 : CoreParser : An exception occurred while parsing the file: System.ArgumentOutOfRangeException, Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at KellyPalRules.KellyPalAnalyzer.CheckSpacingAndNewLine16(CsElement element, CsDocument csdocument)
   at KellyPalRules.KellyPalAnalyzer.VisitElement(CsElement element, CsElement parentElement, CsDocument csdocument)
   at StyleCop.CSharp.CodeWalker`1.VisitElement(CsElement element, CsElement parentElement, T&amp; context)
   at StyleCop.CSharp.CodeWalker`1.WalkElement(CsElement element, CsElement parentElement, T context)
   at StyleCop.CSharp.CodeWalker`1.WalkElement(CsElement element, CsElement parentElement, T context)
   at StyleCop.CSharp.CodeWalker`1.WalkElement(CsElement element, CsElement parentElement, T context)
   at KellyPalRules.KellyPalAnalyzer.AnalyzeDocument(CodeDocument document)
   at StyleCop.StyleCopThread.RunAnalyzers(CodeDocument document, SourceParser parser, IEnumerable`1 analyzers)
   at StyleCop.StyleCopThread.TestAndRunAnalyzers(CodeDocument document, SourceParser parser, IEnumerable`1 analyzers, Int32 passNumber)
   at StyleCop.StyleCopThread.ParseAndAnalyzeDocument(SourceCode sourceCode, DocumentAnalysisStatus documentStatus)
   at StyleCop.StyleCopThread.DoWork(Object sender).</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
          </Reviews>
          <HashCodeIgnoreList />
          <AnalysisFileManager>
            <AnalysisFiles>
              <AnalysisFile>
                <RelativePath>MealData.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MealModel.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>OrderModel.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PosSystem.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PosSystem.Designer.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Program.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\Resources.Designer.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>RestaurantView.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>RestaurantView.Designer.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>StartUpView.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>StartUpView.Designer.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DataGridViewNumericUpDownCell.cs</RelativePath>
                <ProjectName>DataGridViewNumericUpDownElements</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DataGridViewNumericUpDownColumn.cs</RelativePath>
                <ProjectName>DataGridViewNumericUpDownElements</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DataGridViewNumericUpDownEditingControl.cs</RelativePath>
                <ProjectName>DataGridViewNumericUpDownElements</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DataGridViewNumericUpDownElements</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
            </AnalysisFiles>
          </AnalysisFileManager>
        </CodeReview>
      </Data>
    </div>
  </body>
</html>