<html>
  <head>
    <title>Code Review :: </title>
    <style type="text/css">
    .body{background-color:White;}
    .summary{width:100%;font-weight:bold;background-color:White;border: thin solid #808000;color:#FAFCFE}
    .outer{font-weight:normal;color:#6D5757;background-color:#FFDFBF}
    .inner{font-weight:normal;color:black;}
    .reviewTable{border: thin solid #C0C0C0; width:100%}
    .headerRow{color:white;background-color: #800000;font-weight:bold;text-align: center}
    .reviewRow{background-color:#FFDFBF;color:black;}
    .rAligned{text-align:right;}
    .data{visibility:hidden}
  </style>
  </head>
  <body class="body">
    <div class="summary">
      <table>
        <tr>
          <td colspan="3" class="headerRow">Review Summary</td>
        </tr>
        <tr class="outer">
          <td>Project Name : <label class="inner" /></td>
          <td>Reviewed By : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Project Code : <label class="inner" /></td>
          <td>Reviewed Date : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Name : <label class="inner" /></td>
          <td>Status : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Version : <label class="inner" /></td>
          <td>Review Preparation Effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Size (ekloc) : <label class="inner" /></td>
          <td>Review effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Release Date for Review : <label class="inner" /></td>
          <td>Rework effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken By : <label class="inner" /></td>
          <td>Review Efficiency : <label class="inner">NaN</label></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken Date : <label class="inner" /></td>
          <td />
        </tr>
      </table>
      <table>
        <tr class="headerRow">
          <td colspan="2">Review Details</td>
          <td colspan="2">Defect Status Analysis</td>
          <td colspan="2">Defect Type Analysis</td>
          <td colspan="4">Defect Injected Phase Analysis</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td>Major</td>
          <td>Medium</td>
          <td>Minor</td>
        </tr>
        <tr class="outer">
          <td>Total No of Suggestions</td>
          <td class="inner">1</td>
          <td>Open</td>
          <td class="inner">1</td>
          <td>Logical</td>
          <td class="inner">0</td>
          <td>Initial Project Setup</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total No of Errors</td>
          <td class="inner">0</td>
          <td>On Hold</td>
          <td class="inner">0</td>
          <td>Incomplete</td>
          <td class="inner">0</td>
          <td>Project Initiation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total</td>
          <td class="inner">1</td>
          <td>Closed</td>
          <td class="inner">0</td>
          <td>UI</td>
          <td class="inner">0</td>
          <td>Requirement Analysis</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td>Rejected</td>
          <td class="inner">0</td>
          <td>Exception Handling</td>
          <td class="inner">0</td>
          <td>Architecture and Design</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td>Documentation</td>
          <td class="inner">0</td>
          <td>Implementation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>QA Testing</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>Transition Phase</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="rAligned">Total</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
      </table>
    </div>
    <br />
    <table class="reviewTable">
      <tr class="headerRow">
        <td>#</td>
        <td>Description</td>
        <td>Status</td>
        <td>DefectType</td>
        <td>InjectedPhase</td>
      </tr>
      <tr class="reviewRow">
        <td>1</td>
        <td class="inner" />
        <td class="inner">Open</td>
        <td class="inner" />
        <td class="inner">Implementation</td>
      </tr>
    </table>
    <div>
      <br />
    Created with <a href="http://visualstudiogallery.msdn.microsoft.com/d1e40c49-da36-42a5-8d5a-4ebe1feabbc9">ReviewPal</a></div>
    <div class="data">
      <Data id="ReviewPalData">
        <CodeReview xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <Reviews>
            <Review>
              <ReviewId>1</ReviewId>
              <Line>64</Line>
              <Weight>23</Weight>
              <File>PosSystem.cs</File>
              <Project>PosOrderSystem</Project>
              <Status>Open</Status>
              <Comment>Suggestion</Comment>
              <HashCode>LongMethod</HashCode>
              <Severity>Warning</Severity>
              <SmellType>LM0001 : KellyPal : LongMethod</SmellType>
              <InjectedPhase>Implementation</InjectedPhase>
              <RevieweeComment>RevieweeComment</RevieweeComment>
              <ReExamined>No</ReExamined>
              <ReviewerComment>ReviewerComment</ReviewerComment>
            </Review>
          </Reviews>
          <HashCodeIgnoreList />
          <AnalysisFileManager>
            <AnalysisFiles>
              <AnalysisFile>
                <RelativePath>MealModel.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>OrderModel.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PosSystem.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PosSystem.Designer.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Program.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>PosOrderSystem</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
            </AnalysisFiles>
          </AnalysisFileManager>
        </CodeReview>
      </Data>
    </div>
  </body>
</html>